### ISSUE TITLE
ValueError: need at least one array to concatenate

### ISSUE THREAD

**Issue by Bhavana431** [HVision-NKU/Strip-R-CNN#12]
Traceback (most recent call last):
  File "tools\train.py", line 192, in <module>
    main()
  File "tools\train.py", line 181, in main
    train_detector(
  File "c:\users\dell\desktop\strip-r-cnn\strip-r-cnn\mmrotate\apis\train.py", line 141, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "c:\Users\Dell\Desktop\Strip-R-CNN\.conda\lib\site-packages\mmcv\runner\epoch_based_runner.py", line 136, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "c:\Users\Dell\Desktop\Strip-R-CNN\.conda\lib\site-packages\mmcv\runner\epoch_based_runner.py", line 49, in train
    for i, data_batch in enumerate(self.data_loader):
  File "c:\Users\Dell\Desktop\Strip-R-CNN\.conda\lib\site-packages\torch\utils\data\dataloader.py", line 440, in __iter__
    return self._get_iterator()
  File "c:\Users\Dell\Desktop\Strip-R-CNN\.conda\lib\site-packages\torch\utils\data\dataloader.py", line 388, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "c:\Users\Dell\Desktop\Strip-R-CNN\.conda\lib\site-packages\torch\utils\data\dataloader.py", line 1083, in __init__
    self._reset(loader, first_iter=True)
  File "c:\Users\Dell\Desktop\Strip-R-CNN\.conda\lib\site-packages\torch\utils\data\dataloader.py", line 1116, in _reset
    self._try_put_index()
  File "c:\Users\Dell\Desktop\Strip-R-CNN\.conda\lib\site-packages\torch\utils\data\dataloader.py", line 1350, in _try_put_index
    index = self._next_index()
  File "c:\Users\Dell\Desktop\Strip-R-CNN\.conda\lib\site-packages\torch\utils\data\dataloader.py", line 620, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
  File "c:\Users\Dell\Desktop\Strip-R-CNN\.conda\lib\site-packages\torch\utils\data\sampler.py", line 288, in __iter__
    for idx in self.sampler:
  File "c:\Users\Dell\Desktop\Strip-R-CNN\.conda\lib\site-packages\mmdet\datasets\samplers\group_sampler.py", line 36, in __iter__        
    indices = np.concatenate(indices)
  File "<__array_function__ internals>", line 200, in concatenate
ValueError: need at least one array to concatenate

how to solve this one 
dataset i prepared based on the instruction of dataset prepation ms_dota dataset

**Comment by YXB-NKU** [comment]
The ValueError: need at least one array to concatenate arises because the GroupSampler attempts to concatenate an empty list of indices, which occurs when the dataset has no samples. This is most likely due to incorrect paths to images or annotations, or an empty/misformatted annotation file in the training configuration. By verifying and correcting the dataset setup, you should resolve the error and enable training to proceed.

The dataset is empty, likely due to incorrect paths or missing annotations in the configuration. Check and correct the dataset paths and annotation file to ensure data is loaded properly.

**Comment by Bhavana431** [comment]
the previous issue was solved, encounter new issue in mmrotate 

  **File "c:\users\dell\desktop\strip-r-cnn\strip-r-cnn\mmrotate\core\post_processing\bbox_nms_rotated.py", line 62, in multiclass_nms_rotated    
    bboxes, scores, labels = bboxes[inds], scores[inds], labels[inds]
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)**


but added this line in bbox_nms_rotated file still encountering same issue 

 **inds = valid_mask.nonzero(as_tuple=False).squeeze(1)
    inds = inds.to(bboxes.device)
    if inds.numel() == 0:  # If no valid boxes, return empty
        return bboxes.new_zeros((0, bboxes.size(1))), scores.new_zeros((0,)), labels.new_zeros((0,))
    
    bboxes, scores, labels = bboxes[inds], scores[inds], labels[inds]**

**Comment by YXB-NKU** [comment]
The error message confirms that bboxes is on the CPU, and since you’ve added inds = inds.to(bboxes.device), inds should also be on the CPU. However, the error still occurs, which points to a potential issue with the other tensors being indexed: scores and labels.
To resolve the error, ensure that all tensors involved in the indexing operation—bboxes, scores, and labels—are on the same device as inds. Since bboxes is on the CPU and inds is moved to bboxes.device, move scores and labels to bboxes.device as well. This can be done by adding two lines before the indexing operation.

**Comment by Bhavana431** [comment]
Facing this issue after training happened with 12 epochs 

 File "tools\test.py", line 245, in main
    dataset.format_results(outputs, **kwargs)
  File "c:\users\dell\desktop\strip-r-cnn\strip-r-cnn\mmrotate\datasets\dota.py", line 328, in format_results
    id_list, dets_list = self.merge_det(results, nproc)
ValueError: not enough values to unpack (expected 2, got 0)
